// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsz30sOuj3bgiA4RJNFXyH-NuYogv4ccA',
    appId: '1:515842634242:web:0c514dcd6f960a1f632d1b',
    messagingSenderId: '515842634242',
    projectId: 'cats-7c6c1',
    authDomain: 'cats-7c6c1.firebaseapp.com',
    storageBucket: 'cats-7c6c1.appspot.com',
    measurementId: 'G-4V7L3W798R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMScb2EDiDaCDT96lZwgC99Gpjm5AcFRs',
    appId: '1:515842634242:android:4998866c48238d4a632d1b',
    messagingSenderId: '515842634242',
    projectId: 'cats-7c6c1',
    storageBucket: 'cats-7c6c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKmB1MoB4j27o3wBQoZPAhzwq-25_QUfA',
    appId: '1:515842634242:ios:7aafd5fbba5b623b632d1b',
    messagingSenderId: '515842634242',
    projectId: 'cats-7c6c1',
    storageBucket: 'cats-7c6c1.appspot.com',
    iosClientId: '515842634242-j0llpno6402v49698pg63ra86dj1qnsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKmB1MoB4j27o3wBQoZPAhzwq-25_QUfA',
    appId: '1:515842634242:ios:7aafd5fbba5b623b632d1b',
    messagingSenderId: '515842634242',
    projectId: 'cats-7c6c1',
    storageBucket: 'cats-7c6c1.appspot.com',
    iosClientId: '515842634242-j0llpno6402v49698pg63ra86dj1qnsn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cat',
  );
}
